package dev.portalgun.registry;

import dev.portalgun.PortalGunMod;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;

public final class ModSounds {
	public static final SoundEvent PORTAL_OPEN = register("portal.open");
	public static final SoundEvent PORTAL_CLOSE = register("portal.close");
	public static final SoundEvent PORTAL_TRAVEL = register("portal.travel");
	public static final SoundEvent PORTAL_IDLE = register("portal.idle");
	public static final SoundEvent GUN_FIRE = register("gun.fire");
	public static final SoundEvent GUN_EMPTY = register("gun.empty");
	public static final SoundEvent GUN_RELOAD = register("gun.reload");
	public static final SoundEvent GUN_DIAL = register("gun.dial");
	public static final SoundEvent ORB_SHOOT = register("orb.shoot");
	public static final SoundEvent ORB_HIT = register("orb.hit");
	public static final SoundEvent DIMENSION_ARRIVE = register("dimension.arrive");

	/** Looping biome ambiences generated by tools/gen/sounds.py. */
	public static final List<String> AMBIENT_LOOPS = List.of(
		"wind_howl", "alien_hum", "bubbling", "crystal_chimes", "wet_squelch", "electric_buzz", "deep_ocean",
		"volcanic_rumble", "eerie_choir", "jungle_night", "neon_synth", "glitch_noise", "cosmic_drone", "cozy_breeze",
		"clockwork", "candy_chime", "hive_drone", "tidal_waves", "dark_void", "sizzle_toxic"
	);
	public static final Map<String, SoundEvent> AMBIENT = new LinkedHashMap<>();

	static {
		for (String loop : AMBIENT_LOOPS) {
			AMBIENT.put(loop, register("ambient." + loop));
		}
	}

	private ModSounds() {
	}

	private static SoundEvent register(String name) {
		SoundEvent event = SoundEvent.createVariableRangeEvent(PortalGunMod.id(name));
		return Registry.register(BuiltInRegistries.SOUND_EVENT, PortalGunMod.id(name), event);
	}

	public static void init() {
	}
}
