// Dishes cooked through the real food engine (the same calls the stations make), for the
// viewer gallery (?dishes=engine) and the recipe exploration test.
import { makeFood, type FoodState } from '../food/types';
import { applyHeat, applyCold, addSeasoning, blend, combine, cut, enterStation, flatten, mixBowl, peel, potMerge, panMerge, type HeatMethod } from '../food/process';

const F = (id: string, form: FoodState['form'] = 'whole') => makeFood(id, form);
const cook = (f: FoodState, m: HeatMethod, s: number) => {
  for (let t = 0; t < s; t += 0.05) applyHeat(f, m, 0.05);
  return f;
};
const chill = (f: FoodState, s: number) => {
  for (let t = 0; t < s; t += 0.1) applyCold(f, 0.1);
  return f;
};
const cuts = (f: FoodState, n: number) => {
  for (let i = 0; i < n; i++) f = cut(f)!;
  return f;
};
const sea = (f: FoodState, id: string, a = 1) => {
  addSeasoning(f, id, a);
  return f;
};

export function engineDishes(): [string, FoodState][] {
  const rows: [string, FoodState][] = [];
  const add = (label: string, f: FoodState) => rows.push([label, f]);
  add('fries', cook(cuts(peel(F('potato'))!, 3), 'deepfry', 5));
  add('fries salted+ketchup', sea(sea(cook(cuts(peel(F('potato'))!, 3), 'deepfry', 5), 'salt'), 'ketchup'));
  let pizza = flatten(F('dough'))!; sea(pizza, 'tomato-sauce'); pizza = combine(pizza, F('cheese')); pizza = combine(pizza, cut(F('sausage'))!); cook(pizza, 'bake', 6);
  add('pizza pepperoni', pizza);
  let marg = flatten(F('dough'))!; sea(marg, 'tomato-sauce'); marg = combine(marg, cut(F('mozzarella'))!); marg = combine(marg, cut(F('basil'))!); cook(marg, 'bake', 6);
  add('margherita', marg);
  let raw = flatten(F('dough'))!; sea(raw, 'tomato-sauce'); raw = combine(raw, F('cheese'));
  add('raw pizza', raw);
  let burger = combine(cut(F('bun'))!, cook(F('patty'), 'grill', 8)); burger = combine(burger, cut(F('cheese'))!); burger = combine(burger, cut(F('lettuce'))!);
  add('cheeseburger', burger);
  let rawb = combine(cut(F('bun'))!, F('patty')); rawb = combine(rawb, cut(F('cheese'))!);
  add('raw cheeseburger', rawb);
  add('smoothie', blend([F('strawberry'), F('banana'), F('milk')]));
  add('orange juice', blend([F('orange')]));
  add('lemonade', blend([sea(F('lemon'), 'sugar', 1.5)]));
  add('fish milkshake', blend([F('fish'), F('ice-cream'), F('milk')]));
  add('milkshake', blend([F('ice-cream'), F('milk'), F('strawberry')]));
  add('raw chicken', F('chicken'));
  add('burnt toast', cook(cut(F('bread'))!, 'toast', 24));
  add('toast', cook(cut(F('bread'))!, 'toast', 8));
  add('butter toast', combine(cook(cut(F('bread'))!, 'toast', 8), cut(F('butter'))!));
  add('chili', F('chili'));
  add('lemon', F('lemon'));
  const b = enterStation(mixBowl([F('flour'), F('egg'), F('milk')]), 'pan'); cook(b, 'fry', 3);
  add('pancake', b);
  add('pancake honey', sea(cook(enterStation(mixBowl([F('flour'), F('egg'), F('milk')]), 'pan'), 'fry', 3), 'honey'));
  add('blueberry pancake', cook(enterStation(mixBowl([F('flour'), F('egg'), F('milk'), F('blueberry')]), 'pan'), 'fry', 3));
  add('fried egg', cook(enterStation(F('egg'), 'pan'), 'fry', 2.5));
  add('popcorn', cook(F('corn'), 'micro', 5));
  const t = cook(F('tomato', 'diced'), 'boil', 4), o = cook(F('onion', 'diced'), 'boil', 4);
  const soup = potMerge([t, o])!; add('tomato soup', soup);
  add('ice pop', chill(blend([F('strawberry'), F('banana'), F('milk')]), 12));
  add('soup pop', chill(potMerge([cook(F('tomato', 'diced'), 'boil', 4), cook(F('onion', 'diced'), 'boil', 4)])!, 12));
  add('broccoli', F('broccoli'));
  add('boiled broccoli', cook(F('broccoli'), 'boil', 7));
  add('raw onion diced', cuts(F('onion'), 3));
  add('apple', F('apple'));
  add('ice cream', F('ice-cream'));
  add('sundae', sea(sea(F('ice-cream'), 'chocolate-syrup'), 'sprinkles'));
  add('banana split', combine(cut(F('banana'))!, F('ice-cream')));
  add('deep fried ice cream', cook(F('ice-cream'), 'deepfry', 0.5));
  add('boiled banana', cook(F('banana'), 'boil', 8));
  add('fish+chocolate', combine(cook(F('fish'), 'grill', 10), F('chocolate')));
  add('steak grilled', cook(F('steak'), 'grill', 10));
  add('steak rare', cook(F('steak'), 'grill', 4));
  add('sushi', combine(combine(cook(F('rice'), 'boil', 8), cuts(F('salmon'), 1)), F('nori')));
  add('guac', mixBowl([peel(F('avocado'))!, F('lemon'), cuts(F('onion'), 3)]));
  add('salsa', mixBowl([cuts(F('tomato'), 3), cuts(F('onion'), 3), cuts(F('chili'), 2)]));
  add('garden salad', mixBowl([cut(F('lettuce'))!, cuts(F('tomato'), 3), cuts(F('cucumber'), 1)]));
  add('fruit salad', mixBowl([cuts(F('apple'), 3), cuts(F('banana'), 1), F('blueberry')]));
  add('greek salad', mixBowl([cuts(F('tomato'), 3), cuts(F('cucumber'), 2), cuts(F('cheese'), 2)]));
  add('caesar', mixBowl([cut(F('lettuce'))!, cook(cuts(F('bread'), 2), 'bake', 2), cuts(F('cheese'), 2)]));
  add('caprese', combine(combine(cuts(F('tomato'), 2), cut(F('mozzarella'))!), cut(F('basil'))!));
  const om = panMerge([cook(enterStation(mixBowl([F('egg'), F('egg')]), 'pan'), 'fry', 0.3), cuts(F('cheese'), 2)])!; cook(om, 'fry', 3);
  add('cheese omelet', om);
  add('mashed potatoes', mixBowl([cook(F('potato'), 'boil', 10), F('butter')]));
  add('baked potato', cook(F('potato'), 'bake', 10));
  add('hot chocolate', potMerge([cook(F('milk'), 'boil', 4), cook(F('chocolate'), 'boil', 4)])!);
  add('grilled cheese', cook(combine(cut(F('bread'))!, cut(F('cheese'))!), 'fry', 3));
  add('pbj', sea(sea(cut(F('bread'))!, 'peanut-butter'), 'jam'));
  add('hot dog', combine(F('hotdog-bun'), cook(F('sausage'), 'grill', 8)));
  add('fish and chips', combine(cook(F('fish'), 'deepfry', 10), cook(cuts(F('potato'), 3), 'deepfry', 5)));
  add('frozen banana', chill(F('banana'), 10));
  add('frozen pizza', chill(pizza, 12));
  add('cookies', cook(mixBowl([sea(F('flour'), 'sugar'), F('butter'), F('egg'), F('chocolate')]), 'bake', 6));
  add('raw cookie dough', mixBowl([sea(F('flour'), 'sugar'), F('butter'), F('egg')]));
  add('batter raw', mixBowl([F('flour'), F('egg'), F('milk')]));
  add('choc strawberries', combine(F('strawberry'), cook(F('chocolate'), 'micro', 2)));
  add('smores', combine(combine(F('cookie'), cook(F('marshmallow'), 'micro', 1)), F('chocolate')));
  add('onion rings', cook(cuts(F('onion'), 2), 'deepfry', 3));
  add('grilled corn', cook(F('corn'), 'grill', 8));
  add('baked apple', sea(cook(F('apple'), 'bake', 9), 'cinnamon'));
  add('stir fry', panMerge([cook(cuts(F('bell-pepper'), 2), 'fry', 3), cook(cuts(F('onion'), 2), 'fry', 3), cook(cuts(F('steak'), 1), 'fry', 5)])!);
  add('spaghetti pomodoro', sea(cook(F('spaghetti'), 'boil', 8), 'tomato-sauce'));
  add('weird pile', combine(combine(combine(F('gummy'), F('broccoli')), F('fish')), F('ice-cream')));
  add('banana pizza', cook(combine(flatten(F('dough'))!, cut(F('banana'))!), 'bake', 6));
  add('ketchup ice cream', sea(F('ice-cream'), 'ketchup', 1.5));
  add('hot soup fresh', soup);
  add('gummy', F('gummy'));
  add('candy', F('candy'));
  add('donut (pantry)', F('donut'));
  add('fresh donut', cook(F('dough'), 'deepfry', 6));
  add('cake chocolate', cook(mixBowl([F('flour'), F('egg'), F('milk'), F('chocolate')]), 'bake', 6));
  add('carrot cake', cook(mixBowl([F('flour'), F('egg'), F('milk'), cuts(F('carrot'), 2)]), 'bake', 6));
  add('raw egg', F('egg'));
  add('raw potato', F('potato'));
  add('boiled egg', cook(F('egg'), 'boil', 7));
  add('french toast', cook(combine(cut(F('bread'))!, mixBowl([F('egg'), F('milk')])), 'fry', 3));
  add('avocado toast', combine(cook(cut(F('bread'))!, 'toast', 8), cuts(peel(F('avocado'))!, 2)));
  add('tempura', cook(F('shrimp'), 'deepfry', 5));
  add('roast chicken', cook(F('drumstick'), 'bake', 12));
  add('fried chicken', cook(F('drumstick'), 'deepfry', 12));
  add('garlic bread', cook(combine(cut(F('bread'))!, cuts(F('garlic'), 4)), 'bake', 5));
  add('nachos', cook(combine(cuts(F('tortilla'), 2), cuts(F('cheese'), 2)), 'bake', 3));
  add('taco', combine(F('tortilla'), cook(cuts(F('steak'), 2), 'fry', 4)));
  add('quesadilla', cook(combine(F('tortilla'), cuts(F('cheese'), 2)), 'grill', 3));
  add('roasted veggies', cook(combine(cuts(F('carrot'), 1), cuts(F('eggplant'), 1)), 'bake', 7));
  add('squashed apple', flatten(F('apple'))!);
  add('scrambled', cook(enterStation(mixBowl([F('egg'), F('egg')]), 'pan'), 'fry', 3));
  add('mixture fish choc', mixBowl([F('fish'), F('chocolate')]));
  add('watermelon', cut(F('watermelon'))!);
  return rows;
}
