// Levels: separate, endless worlds reached through level doors.
//
// Level 0 is the main building (dimension 0, with its pocket spaces). Level n > 0 lives in
// dimension LEVEL_DIM0 + n and is generated by zone types its module registers for that
// dimension. Every level has doors scattered through it; each door leads to a random level.
//
//   defineLevel(n, {
//     name: 'THALASSOPHOBIA',        // title card and phone
//     zoneType: 'lv7_ocean',         // zone type for every zone, or (ctx) => type, ctx = {story, x0, z0, x1, z1, rand}
//     zoneSize: 64,                  // zone grid in metres: 8, 16, 32, 64, 128 or 256
//     bands: [0],                    // stories (6 m bands) that have content, or 'all'; others are empty
//     entry: { x, y, z, yaw },       // where you step out of the arrival door (y = floor height)
//     doorDensity: 0.55,             // chance that a zone without hand-placed doors gets one
//     sky, weather, grade, light,    // level-wide look (see docs/LEVELS.md); zone env may override
//     script(ctx, dt) {},            // optional per-frame behaviour on the game thread
//   })
import { SB_UNITS, UNIT, LEVEL_H } from '../config.js';
import { defineZone, ZT } from './zonetypes.js';
import { CF, W } from './zonebuilder.js';
import { defineProp, propMat as S, propTex as T } from './props.js';
import { defineTexture } from '../gfx/textures.js';
import { pnoise } from '../gfx/texgen.js';
import { rand3, hash3 } from '../core/rng.js';
import { VF } from './materials.js';

export const LEVEL_DIM0 = 1000;
export const LEVELS = {};
const BY_DIM = new Map();

export const dimOfLevel = (n) => (n === 0 ? 0 : LEVEL_DIM0 + n);
// the level a dimension belongs to (the main building and its pockets are level 0)
export const levelOfDim = (dim) => (dim >= LEVEL_DIM0 ? dim - LEVEL_DIM0 : 0);
export const levelDef = (dim) => LEVELS[levelOfDim(dim)] || null;
export const levelNumbers = () => Object.keys(LEVELS).map(Number).sort((a, b) => a - b);
export const storyOf = (y) => Math.floor((y + 0.05) / LEVEL_H);

export function defineLevel(n, def) {
  const L = Object.assign({
    n, name: 'LEVEL ' + n, dim: dimOfLevel(n), zoneSize: 64, bands: [0],
    entry: { x: 0.5, y: 0, z: 0.5, yaw: 0 }, doorDensity: 0.55,
    sky: null, weather: null, grade: null, light: null, script: null,
  }, def);
  if (n !== 0 && !L.partition) {
    const U = Math.max(1, Math.min(SB_UNITS, Math.round(L.zoneSize / UNIT)));
    L.partition = (story, sbx, sbz) => {
      const out = [];
      const has = L.bands === 'all' || L.bands.includes(story);
      for (let z = 0; z < SB_UNITS; z += U) {
        for (let x = 0; x < SB_UNITS; x += U) {
          const w = Math.min(U, SB_UNITS - x), d = Math.min(U, SB_UNITS - z);
          let type = 'lv_void';
          if (has) {
            if (typeof L.zoneType === 'function') {
              const x0 = sbx * SB_UNITS * UNIT + x * UNIT, z0 = sbz * SB_UNITS * UNIT + z * UNIT;
              type = L.zoneType({ story, x0, z0, x1: x0 + w * UNIT, z1: z0 + d * UNIT, rand: rand3(x0, z0, story * 31 + n, 0x1e7e1) }) || 'lv_void';
            } else type = L.zoneType || 'lv_void';
          }
          out.push({ x, z, w, d, type });
        }
      }
      return out;
    };
  }
  LEVELS[n] = L;
  BY_DIM.set(L.dim, L);
  return L;
}

// dimension definition for the zone map (null for dims that are not levels)
export const levelDimDef = (dim) => (dim >= LEVEL_DIM0 ? BY_DIM.get(dim) || null : null);

// Empty space: stories of a level without content, and unused zones.
defineZone('lv_void', {
  border: 'open', gate: 'open', allowStairs: false, allowPortals: false, allowHoles: false, doors: false,
  params: () => ({}),
  gen(zb) {
    zb.floor.fill(NaN); zb.ceil.fill(NaN); zb.flags.fill(CF.VOID);
    zb.noConnectivity = true;
  },
});

// ------------------------------------------------------------------ the level door
// A plain door standing in its own frame. Warm light leaks from under it and it hums faintly,
// so it can be found by eye and by ear (and by the phone).
defineTexture('lv_door', (p) => {
  p.fill([96, 104, 98]);
  p.noise(6, 0.05, 2);
  p.map((x, y, c) => { const k = 0.94 + 0.06 * pnoise(x * 0.5, y * 3, 32, 7); return [c[0] * k, c[1] * k, c[2] * k]; });
  p.bevel(0, 0, 64, 64, 0.1, 0.22);
  p.bevel(7, 5, 50, 24, 0.08, -0.12);
  p.bevel(7, 34, 50, 25, 0.08, -0.12);
  p.rect(26, 9, 12, 6, [176, 156, 92]);    // number plate
  p.frame(26, 9, 12, 6, [110, 96, 50]);
  p.rect(29, 11, 2, 2, [60, 50, 30]); p.rect(33, 11, 2, 2, [60, 50, 30]);
  p.stain(32, 60, 14, [70, 64, 52], 0.35);
}, 16);
defineTexture('lv_door_frame', (p) => {
  p.fill([62, 58, 52]);
  p.noise(4, 0.06, 2);
  p.map((x, y, c) => { const k = 0.9 + 0.1 * pnoise(x, y * 0.2, 16, 3); return [c[0] * k, c[1] * k, c[2] * k]; });
}, 8);
defineTexture('lv_door_light', (p) => {
  p.fill([255, 226, 168]);
  p.map((x, y, c) => { const k = 0.85 + 0.15 * pnoise(x, 0, 16, 5); return [c[0] * k, c[1] * k, c[2] * k * 0.95]; });
}, 4);

const lightStrip = (name, b) => ({ layer: T(name).layer, flags: VF.FULLBRIGHT, lit: false, color: [0.08, 0.08, 0.08], flk: [b, b, b], chan: 0 });

defineProp('level_door', {
  build(mb, p) {
    const fr = T('lv_door_frame');
    const door = T('lv_door');
    const glow = lightStrip('lv_door_light', 1.15);
    // frame: two posts and a head, threshold flush with the floor
    mb.box(-0.6, 0, -0.11, -0.5, 2.24, 0.11, fr);
    mb.box(0.5, 0, -0.11, 0.6, 2.24, 0.11, fr);
    mb.box(-0.6, 2.14, -0.11, 0.6, 2.3, 0.11, fr);
    // the leaf, a hair above the floor so light shows underneath
    mb.box(-0.48, 0.035, -0.03, 0.48, 2.12, 0.03, [S('metal_dark'), S('metal_dark'), S('metal_dark'), S('metal_dark'), door, door], { uv: ['world', 'world', 'world', 'world', [1, 0, 0, 1], [0, 0, 1, 1]] });
    // light leaking out under the leaf, and a soft spill on the floor both sides
    mb.box(-0.48, 0.0, -0.035, 0.48, 0.035, 0.035, glow);
    const spill = lightStrip('lv_door_light', 0.55);
    mb.quad([-0.46, 0.006, -0.03, 0.46, 0.006, -0.03, 0.4, 0.006, -0.32, -0.4, 0.006, -0.32], [0, 1, 0], spill, [0, 0, 1, 0, 1, 1, 0, 1]);
    mb.quad([0.46, 0.006, 0.03, -0.46, 0.006, 0.03, -0.4, 0.006, 0.32, 0.4, 0.006, 0.32], [0, 1, 0], spill, [0, 0, 1, 0, 1, 1, 0, 1]);
    // handles on both sides
    for (const s of [-1, 1]) mb.box(0.33, 1.0, s * 0.03, 0.42, 1.04, s * 0.075, S('chrome'));
  },
  boxes: [[-0.6, 0, -0.12, 0.6, 2.3, 0.12]],
  use: 'leveldoor',
  light: { y: 0.12, color: [1.0, 0.84, 0.6], rad: 2.8, int: 0.4 },
  emitter: { snd: 'door_hum', y: 1.0, vol: 0.7, rad: 14 },
});

// Place a level door standing on the floor at (x, z), facing direction rot (yaw; the door's
// front faces (sin rot, -cos rot)). y defaults to the cell's floor. Records it for the phone.
export function levelDoor(zb, x, z, rot = 0, opts = {}) {
  const y = opts.y ?? zb.getFloor(Math.floor(x), Math.floor(z));
  const yy = Number.isFinite(y) ? y : 0;
  zb.prop('level_door', x, yy, z, rot, { useY: 1.0, useR: 0.9, ...opts.propOpts });
  zb.doors.push({ x, y: yy, z, rot, arrival: !!opts.arrival });
  return zb.doors[zb.doors.length - 1];
}

// ------------------------------------------------------------------ automatic placement
// After a zone is generated: the arrival door at the level's entry, and (if the generator placed
// none) at most one door on a free spot, with the level's door density.
export function applyLevelDoors(world, zb) {
  const zone = zb.zone;
  const L = levelDef(zone.dim);
  if (!L) return;
  const zt = ZT[zone.type];
  if (!zt || zt.doors === false) return;
  const E = L.entry;
  if (L.n !== 0 && !L.noArrivalDoor && zone.level === storyOf(E.y || 0)) {
    // the door you came through stands right behind the arrival point
    const ax = E.x - Math.sin(E.yaw) * 0.75, az = E.z + Math.cos(E.yaw) * 0.75;
    if (zb.in(Math.floor(ax), Math.floor(az)) && !zb.doors.some((d) => d.arrival)) {
      levelDoor(zb, ax, az, E.yaw, { y: E.y - zone.level * LEVEL_H, arrival: true });
    }
  }
  if (zb.doors.some((d) => !d.arrival)) return;
  let density = zt.doorDensity ?? L.doorDensity;
  if (L.n === 0) {
    if (zone.dim !== 0) return;                       // pockets have their own way out
    if (zone.ctx && zone.ctx.flatDist < 70 && zone.level === 0) return;   // keep the first hall calm
    // bigger zones are likelier to hold one
    density = Math.min(0.85, density * ((zone.x1 - zone.x0) * (zone.z1 - zone.z0)) / (64 * 64));
  }
  if (rand3(zone.x0, zone.z0, zone.level * 977 + zone.dim, 0xd00d) >= density) return;
  const spot = findDoorSpot(zb);
  if (spot) levelDoor(zb, spot.x, spot.z, spot.rot);
}

// A free cell with a clear 3x3 neighbourhood on flat floor, away from props and gates.
export function findDoorSpot(zb, margin = 2) {
  const { x0, z0, x1, z1 } = zb;
  const w = x1 - x0 - margin * 2, d = z1 - z0 - margin * 2;
  if (w < 3 || d < 3) return null;
  const occ = new Uint8Array((x1 - x0) * (z1 - z0));
  const mark = (x, z, r) => {
    for (let zz = Math.floor(z - r); zz <= Math.floor(z + r); zz++) for (let xx = Math.floor(x - r); xx <= Math.floor(x + r); xx++) {
      if (xx >= x0 && xx < x1 && zz >= z0 && zz < z1) occ[(zz - z0) * (x1 - x0) + (xx - x0)] = 1;
    }
  };
  for (const p of zb.props) mark(p.x, p.z, 1.0);
  for (const p of zb.dynamics) mark(p.x, p.z, 1.5);
  for (const b of zb.brushes) for (let zz = Math.floor(b.z0); zz < Math.ceil(b.z1); zz++) for (let xx = Math.floor(b.x0); xx < Math.ceil(b.x1); xx++) mark(xx + 0.5, zz + 0.5, 0.5);
  const n = w * d;
  const start = hash3(zb.zone.x0, zb.zone.z0, zb.zone.level) % n;
  const stride = coprimeStride(n, hash3(zb.zone.z0, zb.zone.x0, 7));
  const tries = Math.min(n, 400);
  for (let k = 0; k < tries; k++) {
    const c = (start + k * stride) % n;
    const cx = x0 + margin + (c % w), cz = z0 + margin + Math.floor(c / w);
    if (doorCellOk(zb, cx, cz, occ)) {
      const rot = (hash3(cx, cz, 11) % 4) * Math.PI / 2;
      return { x: cx + 0.5, z: cz + 0.5, rot };
    }
  }
  return null;
}

function coprimeStride(n, h) {
  const gcd = (a, b) => (b ? gcd(b, a % b) : a);
  let s = (h % (n - 1)) + 1;
  while (gcd(s, n) !== 1) s = (s % (n - 1)) + 1;
  return s;
}

function doorCellOk(zb, cx, cz, occ) {
  const f = zb.getFloor(cx, cz);
  if (!Number.isFinite(f)) return false;
  for (let dz = -1; dz <= 1; dz++) for (let dx = -1; dx <= 1; dx++) {
    const x = cx + dx, z = cz + dz;
    if (!zb.in(x, z)) return false;
    const i = zb.i(x, z);
    if (zb.solid[i] || occ[i]) return false;
    if (zb.flags[i] & (CF.VOID | CF.STAIRS | CF.GATE | CF.KEEP)) return false;
    const ff = zb.floor[i];
    if (!Number.isFinite(ff) || Math.abs(ff - f) > 0.05) return false;
    const c = zb.ceil[i];
    if (Number.isFinite(c) && c - ff < 2.5) return false;
    // no walls inside the 3x3 block
    if (dx > -1 && zb.wallW[i] !== W.NONE) return false;
    if (dz > -1 && zb.wallN[i] !== W.NONE) return false;
  }
  return true;
}

// ------------------------------------------------------------------ finding doors
// All doors of the zones within r metres of (x, z) on a story (and the stories next to it),
// generating those zones if needed. Absolute coordinates.
export function findDoors(world, dim, story, x, z, r) {
  const out = [];
  const seen = new Set();
  const L = levelDef(dim);
  // multi-storey levels also look one story up and down; elsewhere only the current story
  const multi = L && L.n !== 0 && (L.bands === 'all' || L.bands.length > 1);
  const stories = multi ? [story - 1, story, story + 1].filter((s) => L.bands === 'all' || L.bands.includes(s)) : [story];
  for (const st of stories) {
    for (let zz = Math.floor((z - r) / UNIT) * UNIT; zz <= z + r; zz += UNIT) {
      for (let xx = Math.floor((x - r) / UNIT) * UNIT; xx <= x + r; xx += UNIT) {
        const zone = world.zoneAt(dim, st, xx + 1, zz + 1);
        if (!zone || seen.has(zone.key)) continue;
        seen.add(zone.key);
        if (zone.type === 'lv_void' || zone.type === 'claimed') continue;
        const zb = world.builder(zone);
        for (const d of zb.doors) out.push({ x: d.x, y: d.y + st * LEVEL_H, z: d.z, rot: d.rot, arrival: d.arrival });
      }
    }
  }
  return out;
}
