// Scraps of paper found around the building. Kept deliberately mundane and unexplained.
export const NOTES = [
  'MEMO\nTo: All floor staff\nRe: Lighting\n\nThe lights on this floor will remain on at all times.\n\nPlease do not report the buzzing. The buzzing is normal.\n\n- Facilities',
  'INVENTORY, AISLE 14\n\nChairs (folding) ..... 1,204\nChairs (folding) ..... 1,204\nChairs (folding) ..... 1,205\n\nRecount Monday.',
  'Week 41 - carpet cleaning postponed.\nWeek 42 - carpet cleaning postponed.\nWeek 43 - carpet cleaning postponed.\nWeek 44 - the carpet is fine.',
  'PLEASE RETURN THE STAPLER\nTO ROOM 3-117.',
  'Meeting moved to the conference room on the other side.\n\nFollow the hallway until it ends.\n\nIt will end.',
  'FLOOR PLAN - REVISION 7\n\nRooms added: 40\nRooms removed: 0\n\nAPPROVED',
  'Do not prop open the fire doors.\nThe fire doors must remain closed at all times.\n\nThere are no fire doors on this floor.',
  'LOST: blue umbrella.\n\nIf found, please leave it by the water cooler.\n\nAny water cooler.',
  'to do\n- call building management\n- call building management\n- find the lobby\n- water the plant',
  'REMINDER\n\nThe 5:00 bell no longer rings.\nPlease leave when you are finished.',
  'MAINTENANCE LOG B-14\n\n02:10  HVAC cycled\n02:40  HVAC cycled\n03:10  HVAC cycled\n03:11  HVAC cycled\n03:11  HVAC cycled',
  'This vending machine accepts exact change only.\n\nNobody has exact change.',
  'VISITOR SIGN-IN\n\nName: ______________\nName: ______________\nName: ______________\nName: ______________\nName: ______________',
  'Please do not take the chairs.\nThey belong to this room.\n\nThey will be returned.',
  '[a crayon drawing of a yellow room. inside it, a smaller yellow room. inside that, a smaller one.]',
  'EMPLOYEE HANDBOOK, p. 214\n\n...walk until the carpet changes. If the carpet does not change, you have not walked far enough.',
  'Thank you for your patience.\n\nYour floor is being prepared.',
  'Hallway C, measured: 31.5 m\nMeasured again: 31.5 m\nMeasured from the other end: 48 m',
  'ELEVATOR OUT OF SERVICE.\nPLEASE USE THE STAIRS.\n\nSTAIRS OUT OF SERVICE.\nPLEASE USE THE ELEVATOR.',
  'The phones here still work.\n\nNobody answers, but they still work.',
  'If you get lost, count the lights.\nThen count them again.',
  'Whoever keeps moving the plant back to this desk:\nthank you, I suppose.',
  'Day 1: took the stairs down to find the exit.\nDay 2: took the stairs down.\nDay 3: the stairs are longer than yesterday.',
  'NOTICE\n\nThe air conditioning will be switched off for maintenance.\n\nIt will be switched back on.',
  'Lunch in the break room, 12:00.\nBring a chair.\nBring several chairs.',
  'I left the light on in the copy room so you could find your way back.\n\nIf it is off, it was not me.',
  'FLOOR 0 / FLOOR 0 / FLOOR 0\nplease confirm floor number',
  'Quarterly review:\n\nOccupancy - stable\nSquare footage - increasing\nExits - under review',
  'The rooms on the north side are larger than the building.\nThis has been reported.',
  'Out sick.\nBack Monday.\n(which Monday?)',
  'Re: the humming in the walls\n\nIt is the building. The building is fine.',
  'TO WHOEVER IS NEXT\n\nThe water cooler on 4 is always full. I do not know who fills it. Drink it anyway.',
  'Remember: every hallway ends somewhere.\nThat is what hallways are for.',
  'Please keep this door closed.\nPlease keep this door open.\n(see attached revision)',
  'RECEIPT\n1x coffee .......... 0.75\n1x coffee .......... 0.75\n1x coffee .......... 0.75\nTOTAL ............. 0.75',
  'Parking garage level 2 is closed.\nThere is no parking garage.\nLevel 2 remains closed.',
];

export function noteText(i) { return NOTES[((i % NOTES.length) + NOTES.length) % NOTES.length]; }
