// Original survivor dialogue. Personalities: Bill (grizzled veteran, leader,
// dry, protective, calls people "kid"), Zoey (film student, horror-movie
// buff, quick wit), Louis (IT analyst, relentlessly upbeat, practical),
// Francis (biker, confrontational, hates everything, secretly loyal).
export const LINES = {
  bill: {
    reload: ['Reloading!', 'Changing mags, cover me.', 'Reloading - keep \'em off me.'],
    hordeIncoming: ['Here they come!', 'Heads up, big group incoming!', 'Horde! Form up!', 'Hear that? Get ready.'],
    tankSpotted: ['TANK! Everybody scatter and pour it on!', 'Big one! Tank! Keep your distance!', 'Tank! Don\'t let it get close!'],
    witchSpotted: ['Witch. Lights off, give her room.', 'Hold up - there\'s a Witch. Nobody spook her.', 'Hear the crying? Witch. Walk wide.'],
    hunterSpotted: ['Hunter!', 'Hunter - watch the shadows.', 'Hunter out there, stay together.'],
    smokerSpotted: ['Smoker!', 'Smoker, up high!', 'Smoker - watch for that tongue.'],
    boomerSpotted: ['Boomer! Don\'t shoot it close!', 'Boomer - shove it back first.', 'Fat one! Boomer!'],
    incapped: ['I\'m down! Somebody get me up!', 'Help! I\'m down here!', 'Legs gave out - need a hand!'],
    reviving: ['Hang on, I got you.', 'Up you get, soldier.', 'Grab my hand.'],
    revived: ['Thanks. Owe you one.', 'Appreciate it.', 'Good. Back in the fight.'],
    healSelf: ['Patching myself up.', 'Hold the line, I\'m bandaging.'],
    healOther: ['Hold still, I\'ll fix you up.', 'You look like hell. Let me patch that.'],
    healed: ['Thanks, I needed that.', 'Much obliged.'],
    pills: ['Taking pills.', 'Pills. That\'s better.'],
    givePills: ['Here - take these.', 'Pills. You need \'em more than me.'],
    lowHealth: ['I\'m hurt bad.', 'Can\'t take much more of this.', 'I\'m bleeding pretty good here.'],
    friendlyFire: ['Watch your fire!', 'Hey! I\'m on your side!', 'Check your targets, dammit!'],
    ffSorry: ['My fault.', 'Sorry! Sorry.'],
    killedSpecial: ['Got it.', 'That one\'s done.', 'Scratch one.'],
    killedTank: ['Tank\'s down. Hell of a thing.', 'Big bastard\'s dead!'],
    pinnedHunter: ['Get it off me!', 'Hunter! Get it off!'],
    pinnedSmoker: ['Smoker\'s got me!', 'Cut me loose!'],
    biled: ['Boomer got me - they\'re coming!', 'Aw hell, I\'m covered in it!'],
    throwPipe: ['Pipe bomb out!', 'Fire in the hole!'],
    throwMolotov: ['Molotov!', 'Burn \'em!'],
    spotAmmo: ['Ammo here.', 'Ammo, grab some.'],
    spotHealth: ['Medkits here.', 'First aid over here.'],
    spotWeapons: ['Weapons here.', 'Guns. Grab what you can carry.'],
    teammateDied: ['Damn it. We lost one.', 'No... not like this.'],
    witchStartled: ['She\'s up! Run!', 'Witch is pissed - move!'],
    lead: ['This way.', 'Move it, people.', 'Stay close. Keep moving.'],
    safeRoom: ['Safe room! Everybody in!', 'Get in here and shut that door!'],
    closeDoor: ['Close the door.', 'Somebody get that door.'],
    carAlarm: ['Who touched the car?!', 'Perfect. Just perfect.'],
    idle: ['Seen worse than this. Not much worse.', 'Keep your eyes open.', 'Don\'t get comfortable.'],
    thanks: ['Thanks.', 'Good work.'],
  },
  zoey: {
    reload: ['Reloading!', 'Cover me, I\'m reloading!', 'Changing clips!'],
    hordeIncoming: ['Oh, here they come!', 'Horde! Lots of them!', 'Incoming! Big group!'],
    tankSpotted: ['TANK! Oh god, TANK!', 'Tank! Tank! Run!', 'Tank - spread out!'],
    witchSpotted: ['Witch. Nobody touch her.', 'There\'s a Witch - flashlights off!', 'Hear that crying? That\'s never good.'],
    hunterSpotted: ['Hunter!', 'Hunter, somewhere close!'],
    smokerSpotted: ['Smoker!', 'Smoker up there!'],
    boomerSpotted: ['Boomer!', 'Boomer - shove him, don\'t pop him!'],
    incapped: ['I\'m down! Help!', 'Somebody help me up!', 'I can\'t get up!'],
    reviving: ['Come on, get up!', 'I\'ve got you, come on!'],
    revived: ['Thanks, I thought that was it.', 'Thank you!'],
    healSelf: ['Healing, cover me.', 'Give me a sec, bandaging.'],
    healOther: ['Hold still, I\'m patching you up.', 'Let me fix that.'],
    healed: ['Thanks, that\'s better.', 'Thank you!'],
    pills: ['Popping pills.', 'Taking some pills.'],
    givePills: ['Here, take these.', 'Pills - take them.'],
    lowHealth: ['I\'m hurt pretty bad.', 'I don\'t feel so good.', 'I\'m really hurting here.'],
    friendlyFire: ['Hey! Watch it!', 'Quit shooting me!', 'Friendly fire, genius!'],
    ffSorry: ['Sorry!', 'Oops. My bad.'],
    killedSpecial: ['Got him!', 'Nailed it.', 'And stay down.'],
    killedTank: ['We killed a Tank. We actually killed a Tank.', 'Tank\'s dead! Holy crap!'],
    pinnedHunter: ['Get him off me!', 'Help! Hunter!'],
    pinnedSmoker: ['Smoker\'s got me!', 'Help! It\'s pulling me!'],
    biled: ['Ugh! I\'m covered in puke!', 'Oh god, it\'s in my mouth!'],
    throwPipe: ['Pipe bomb!', 'Throwing a pipe bomb!'],
    throwMolotov: ['Molotov out!', 'Throwing a Molotov!'],
    spotAmmo: ['Ammo over here.', 'Found ammo!'],
    spotHealth: ['Medkits here!', 'First aid kits!'],
    spotWeapons: ['Guns over here!', 'Weapons!'],
    teammateDied: ['No! No, no, no...', 'We lost them...'],
    witchStartled: ['She\'s coming! RUN!', 'You woke her up!'],
    lead: ['This way!', 'Over here!'],
    safeRoom: ['Safe room! Let\'s go!', 'In here, hurry!'],
    closeDoor: ['Close the door!', 'Shut it, shut it!'],
    carAlarm: ['Really? The car alarm?', 'Oh, that\'s great. That\'s just great.'],
    idle: ['In the movies this is where somebody wanders off alone. Nobody wander off.', 'This is the part where the music gets quiet.', 'I used to think this stuff was fun to watch.'],
    thanks: ['Thanks!', 'Nice one.'],
  },
  louis: {
    reload: ['Reloading!', 'Reloading, gimme a sec!', 'Out! Reloading!'],
    hordeIncoming: ['Here they come!', 'Uh, guys? That\'s a lot of them!', 'Horde incoming!'],
    tankSpotted: ['TANK!', 'Tank! Big one! Run!', 'Tank! Everybody shoot it!'],
    witchSpotted: ['Witch. Let\'s just... not.', 'Witch up ahead. Nice and quiet.', 'There\'s a Witch. Everybody be cool.'],
    hunterSpotted: ['Hunter!', 'Hunter nearby!'],
    smokerSpotted: ['Smoker!', 'Smoker, watch it!'],
    boomerSpotted: ['Boomer!', 'Boomer - don\'t let him get close!'],
    incapped: ['I\'m down! I\'m down!', 'Help me up, guys!', 'Little help here!'],
    reviving: ['Come on, up you go!', 'I got you, man.'],
    revived: ['Thanks, man!', 'You\'re the best.'],
    healSelf: ['Healing up!', 'Using my medkit.'],
    healOther: ['Hold on, I\'ll patch you up.', 'Let me get that for you.'],
    healed: ['Thanks! I feel great!', 'Much better, thank you!'],
    pills: ['Pills! Oh yeah.', 'Taking pills - these things are great.'],
    givePills: ['Here - pills! Take \'em!', 'Pills for you.'],
    lowHealth: ['I\'m hurt, guys.', 'Man, I\'m not doing so good.', 'I need some medical attention.'],
    friendlyFire: ['Ow! Hey!', 'Stop shooting me, man!', 'Friendly! Friendly!'],
    ffSorry: ['Sorry! Sorry, man!', 'That was me. Sorry.'],
    killedSpecial: ['Got him!', 'Yes! Got \'em!', 'Down he goes!'],
    killedTank: ['We did it! Tank\'s dead!', 'Woo! Tank down!'],
    pinnedHunter: ['Get it off! Get it off!', 'Hunter! Help!'],
    pinnedSmoker: ['Smoker got me! Help!', 'It\'s choking me!'],
    biled: ['Ugh, I got puked on!', 'Aw man, that is nasty!'],
    throwPipe: ['Pipe bomb!', 'Pipe bomb out!'],
    throwMolotov: ['Molotov!', 'Fire!'],
    spotAmmo: ['Ammo here!', 'Got ammo!'],
    spotHealth: ['Pills here!', 'Medkits! And pills!'],
    spotWeapons: ['Weapons here!', 'Guns, guys!'],
    teammateDied: ['Oh no... oh man.', 'We lost one...'],
    witchStartled: ['Oh no. RUN!', 'She\'s mad! Run!'],
    lead: ['Come on, this way!', 'Let\'s go, let\'s go!'],
    safeRoom: ['Safe room! Come on!', 'In here! Safe room!'],
    closeDoor: ['Close that door!', 'Door! Door!'],
    carAlarm: ['Who set off the alarm?!', 'Aw, come on!'],
    idle: ['Could be worse. Could be Monday.', 'We\'re gonna make it. I can feel it.', 'Anybody else starving?'],
    thanks: ['Thanks!', 'Nice!'],
  },
  francis: {
    reload: ['Reloading!', 'Reloading, and I hate it!', 'Cover me, reloading.'],
    hordeIncoming: ['Here they come!', 'Company!', 'Oh, you want some? Come get some!'],
    tankSpotted: ['TANK! Oh, I hate Tanks!', 'Tank! Big ugly son of a...', 'Tank! Light him up!'],
    witchSpotted: ['Witch. Somebody else deal with her.', 'Witch. Great. I hate Witches.', 'Crying lady. Stay away from the crying lady.'],
    hunterSpotted: ['Hunter!', 'Hunter. Man, I hate those things.'],
    smokerSpotted: ['Smoker!', 'Smoker. I hate smokers.'],
    boomerSpotted: ['Boomer!', 'Fat boy incoming - Boomer!'],
    incapped: ['I\'m down! Somebody get over here!', 'Help me up! Now!', 'Hey! Down here!'],
    reviving: ['Get up. Come on.', 'On your feet.'],
    revived: ['About time.', 'Yeah, yeah. Thanks.'],
    healSelf: ['Patching up. Don\'t get used to it.', 'Healing.'],
    healOther: ['Hold still or I stop.', 'I\'ll fix you. Don\'t cry about it.'],
    healed: ['Thanks. I guess.', 'Yeah. That\'s better.'],
    pills: ['Pills. Breakfast of champions.', 'Taking pills.'],
    givePills: ['Take these. Don\'t say I never gave you nothin\'.', 'Here. Pills.'],
    lowHealth: ['I\'m hurt. Bad.', 'Okay, that one hurt.', 'I\'m bleeding all over the place here.'],
    friendlyFire: ['Hey! Shoot THEM, not me!', 'Watch it, jackass!', 'Do that again and see what happens.'],
    ffSorry: ['Whoops.', 'Yeah, that was me. Get over it.'],
    killedSpecial: ['Got him!', 'Ha! Dead.', 'That\'s what I\'m talking about.'],
    killedTank: ['Tank\'s dead! Who\'s next?!', 'That\'s one dead Tank. I love this.'],
    pinnedHunter: ['Get this thing off me!', 'Hunter! Kill it!'],
    pinnedSmoker: ['Smoker\'s got me!', 'Cut the damn tongue!'],
    biled: ['Aw, gross! I hate Boomers!', 'I\'m covered in boomer crap!'],
    throwPipe: ['Pipe bomb!', 'Pipe bomb! Party time!'],
    throwMolotov: ['Molotov! Burn, baby!', 'Throwing fire!'],
    spotAmmo: ['Ammo.', 'Ammo here.'],
    spotHealth: ['Medkits.', 'First aid.'],
    spotWeapons: ['Guns! Now we\'re talking.', 'Weapons here.'],
    teammateDied: ['Damn it...', 'They got one of us...'],
    witchStartled: ['She\'s up! Run!', 'Crying lady\'s mad! Go go go!'],
    lead: ['This way.', 'Move it.'],
    safeRoom: ['Safe room! Get in!', 'In here!'],
    closeDoor: ['Close the door.', 'Door. Now.'],
    carAlarm: ['Who did that?!', 'Great. I hate car alarms.'],
    idle: ['I hate this city.', 'I hate stairs. Just so you know.', 'Everybody stop looking at me like that.'],
    thanks: ['Thanks.', 'Yeah.'],
  },
};

// Scripted conversations. who: bill|zoey|louis|francis|pilot|news|radio
export const SCRIPTS = {
  introChopper: [
    { who: 'news', text: 'Attention! This is News Chopper Five. If anyone can hear this, make your way to Mercy Hospital!', d: 0 },
    { who: 'news', text: 'Evacuation is under way from the hospital roof. Repeat: Mercy Hospital.', d: 4.5 },
    { who: 'bill', text: 'You heard the man. Mercy Hospital.', d: 9 },
    { who: 'zoey', text: 'How far is that?', d: 11.5 },
    { who: 'louis', text: 'Across the city. Subway runs right by it.', d: 13.5 },
    { who: 'francis', text: 'Great. Subways. I hate subways.', d: 16 },
  ],
  ch1Start: [
    { who: 'bill', text: 'Grab everything you can carry. We\'re not coming back up here.', d: 0 },
  ],
  ch1Street: [
    { who: 'zoey', text: 'The whole street... everyone\'s just gone.', d: 0 },
    { who: 'bill', text: 'Not gone, kid. Just changed. Keep your gun up.', d: 3 },
  ],
  ch1Subway: [
    { who: 'louis', text: 'There! The subway entrance!', d: 0 },
    { who: 'bill', text: 'Let\'s get off these streets.', d: 2.5 },
  ],
  ch1Safe: [
    { who: 'louis', text: 'We made it through one level of hell. How many more?', d: 1 },
    { who: 'francis', text: 'Knowing our luck? All of them.', d: 4 },
  ],
  ch2Start: [
    { who: 'bill', text: 'Tunnels. Stay tight and watch the tracks.', d: 0.5 },
    { who: 'zoey', text: 'Dark tunnel, dead city, creepy noises. I\'ve seen this movie.', d: 3.5 },
    { who: 'francis', text: 'How does it end?', d: 7 },
    { who: 'zoey', text: 'Depends if it\'s the director\'s cut.', d: 8.5 },
  ],
  ch2Generator: [
    { who: 'louis', text: 'This gate runs on the generator. If I start it up, it\'s going to be loud.', d: 0 },
    { who: 'bill', text: 'Then get ready for company. Everybody find cover.', d: 3.5 },
  ],
  ch2Safe: [
    { who: 'francis', text: 'A pawn shop. Figures. Everything here\'s overpriced.', d: 1 },
    { who: 'louis', text: 'Hey, we\'re alive and it\'s free. Best deal in town.', d: 4 },
  ],
  ch3Start: [
    { who: 'bill', text: 'Hospital\'s on the other side of the sewer. We go under.', d: 0.5 },
    { who: 'francis', text: 'Sewers. Add it to the list.', d: 3.5 },
    { who: 'zoey', text: 'What list?', d: 5.5 },
    { who: 'francis', text: 'The list of stuff I hate.', d: 7 },
  ],
  ch3Lift: [
    { who: 'louis', text: 'That lift will get us up to the warehouse roof!', d: 0 },
    { who: 'bill', text: 'And it\'s going to make one hell of a racket. Stock up first.', d: 3 },
  ],
  ch3Hospital: [
    { who: 'zoey', text: 'Mercy Hospital! There it is!', d: 0 },
    { who: 'louis', text: 'I have never been so happy to see a hospital.', d: 2.5 },
  ],
  ch3Safe: [
    { who: 'bill', text: 'Rest up. It\'s a long way to the roof.', d: 1 },
  ],
  ch4Start: [
    { who: 'louis', text: 'Elevators should take us to the upper floors.', d: 0.5 },
    { who: 'francis', text: 'I hate elevators almost as much as I hate hospitals.', d: 3.5 },
    { who: 'bill', text: 'You hate everything.', d: 6.5 },
    { who: 'francis', text: 'I don\'t hate you, Bill. Yet.', d: 8 },
  ],
  ch4Elevator: [
    { who: 'bill', text: 'Call the elevator. Then dig in - they\'ll hear it.', d: 0 },
  ],
  ch4ElevatorArrive: [
    { who: 'louis', text: 'Elevator\'s here! Everybody in!', d: 0 },
  ],
  ch4Safe: [
    { who: 'zoey', text: 'Almost there. One more floor.', d: 1 },
    { who: 'bill', text: 'The roof. Whatever\'s up there, we face it together.', d: 3.5 },
  ],
  ch5Start: [
    { who: 'louis', text: 'There\'s a radio over there - let\'s call the chopper!', d: 0.5 },
  ],
  radio1: [
    { who: 'bill', text: 'Hello? Anybody reading this? We\'re on the roof of Mercy Hospital!', d: 0 },
    { who: 'pilot', text: 'Copy that, I hear you! You\'re alive up there? Hold tight - I\'m on my way. Get ready, and call me again when you are.', d: 4 },
  ],
  radio2: [
    { who: 'zoey', text: 'We\'re ready! Come get us!', d: 0 },
    { who: 'pilot', text: 'Alright, I\'m inbound. It\'s going to take some time - hold your position!', d: 3 },
    { who: 'bill', text: 'Everybody, here they come! Hold this roof!', d: 7 },
  ],
  pilotUpdate1: [{ who: 'pilot', text: 'Hang on down there! I\'m about ten minutes out!', d: 0 }],
  pilotUpdate2: [{ who: 'pilot', text: 'Still coming! Keep that helipad clear for me!', d: 0 }],
  pilotUpdate3: [{ who: 'pilot', text: 'Almost there, almost there! I can see the fires from here!', d: 0 }],
  pilotArrive: [
    { who: 'pilot', text: 'I\'m here! Get to the chopper, now!', d: 0 },
    { who: 'louis', text: 'Chopper\'s here! GO GO GO!', d: 2 },
  ],
  escape: [
    { who: 'pilot', text: 'Hold on to something! We\'re out of here!', d: 0 },
    { who: 'zoey', text: 'We made it... we actually made it.', d: 3.5 },
    { who: 'bill', text: 'For now, kid. For now.', d: 6.5 },
    { who: 'francis', text: 'Hey, pilot. You\'re looking a little pale.', d: 9.5 },
  ],
};
