package com.laptopcraft.content;

import com.laptopcraft.LaptopCraft;
import com.laptopcraft.registry.Reg;
import com.laptopcraft.shop.Catalog;
import com.laptopcraft.shop.Categories;
import com.laptopcraft.shop.Product;
import java.util.List;
import java.util.Optional;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.decoration.painting.PaintingVariant;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import org.jspecify.annotations.Nullable;

/**
 * Custom painting variants sold on Emerazon. The variants themselves are data-driven
 * ({@code data/laptopcraft/painting_variant/*.json}, generated by {@code tools/art/food/paintings.py});
 * this class only knows their ids for the shop and the creative tab.
 */
public final class PaintingContent {
	/** One gallery piece: painting variant id (in the laptopcraft namespace) plus shop data. */
	public record Masterpiece(String id, String title, int width, int height, int price, String description, int rating, int reviews, String badge) {
		public ResourceKey<PaintingVariant> key() {
			return ResourceKey.create(Registries.PAINTING_VARIANT, Reg.id(id));
		}
	}

	public static final List<Masterpiece> GALLERY = List.of(
			new Masterpiece("mona_llama", "Mona Llama", 2, 3, 18,
					"Leonardo da Villager's most famous portrait. Her smile follows you around the room. So does she, if you have hay.",
					49, 4210, "Best Seller"),
			new Masterpiece("starry_night_sky", "The Starry Night Sky", 4, 3, 20,
					"Swirling stars over a sleepy blocky village. Vincent van Golem painted it with one ear on the ground listening for zombies.",
					50, 3874, "Limited"),
			new Masterpiece("creeper_scream", "The Creeper Scream", 2, 2, 12,
					"An existential Creeper on a bridge at sunset. Experts agree: it's not screaming, it's hissing.",
					46, 1920, ""),
			new Masterpiece("sunflower_field", "Sunflower Field", 4, 2, 14,
					"Endless sunflowers all facing east, as sunflowers do. Painted at sunrise by Claude Mobnet.",
					47, 1302, ""),
			new Masterpiece("great_wave", "The Great Wave", 3, 2, 16,
					"A towering blocky wave off the coast of a mushroom island. A Drowned is surfing it, apparently.",
					48, 2188, "Best Seller"),
			new Masterpiece("emerald_earring", "Villager with an Emerald Earring", 2, 2, 15,
					"Johannes Ver-Miner's mysterious villager glancing over their shoulder. The earring costs more than the painting.",
					48, 1777, ""),
			new Masterpiece("redstone_composition", "Composition with Redstone", 2, 2, 8,
					"Piet Minedrian's abstract masterpiece: red, yellow, blue and a strong signal of 15. Fully powered modern art.",
					43, 640, "Deal"),
			new Masterpiece("dragon_sunset", "Ender Dragon Sunset", 4, 2, 17,
					"The Dragon soaring through a violet sunset over the End islands. Painted from a safe distance (one Endermite).",
					47, 1450, ""),
			new Masterpiece("cherry_grove_dawn", "Cherry Grove at Dawn", 3, 2, 12,
					"Pink petals drift over a quiet pond as the sun comes up. The most peaceful biome, now on your wall.",
					49, 2604, "New"),
			new Masterpiece("diamond_still_life", "Still Life with Diamond Ore", 2, 2, 10,
					"Paul Cobblezanne's study of a diamond pickaxe, an apple and a block of diamond ore. Do not mine the painting.",
					45, 880, ""),
			new Masterpiece("steve_portrait", "Portrait of Steve", 1, 1, 4,
					"A humble self-portrait. Steve claims he painted it; Alex claims she held the brush.",
					41, 512, "Deal"),
			new Masterpiece("netherhawks", "Netherhawks", 3, 2, 14,
					"Late-night customers at a Nether Fortress diner. The Blaze behind the counter makes a mean grilled cheese.",
					46, 990, ""),
			new Masterpiece("villager_gothic", "Villager Gothic", 2, 2, 11,
					"A stern farmer villager couple and their trusty hoe. They will not trade with you. Hmm.",
					44, 731, ""),
			new Masterpiece("persistence_of_mining", "The Persistence of Mining", 3, 2, 13,
					"Salvador Dallay's melting clocks draped over a desert. That's what happens when you mine all night.",
					46, 1033, "New"),
			new Masterpiece("creation_of_steve", "The Creation of Steve", 4, 1, 16,
					"The divine hand passes a diamond to Steve. Michelangelo Buonarr-oak-ti spent four years on a scaffold of dirt.",
					48, 1544, "Limited")
	);

	private PaintingContent() {
	}

	/** Registers blocks/items. Called during mod init, before the catalog is built. */
	public static void init() {
	}

	/** Adds this group's products to the {@link com.laptopcraft.shop.Catalog}. */
	public static void addProducts() {
		for (Masterpiece art : GALLERY) {
			String name = art.title() + " (" + art.width() + "×" + art.height() + ")";
			Catalog.register(Product.emerazon("painting/" + art.id(), Categories.PAINTINGS, name, art.description(), art.price(),
					registries -> paintingStack(registries, art), art.rating(), art.reviews(), art.badge()));
		}
	}

	/** Adds painting items carrying this mod's painting variants to the LaptopCraft creative tab. */
	public static void fillCreativeTab(CreativeModeTab.ItemDisplayParameters parameters, CreativeModeTab.Output output) {
		for (Masterpiece art : GALLERY) {
			variant(parameters.holders(), art).ifPresent(holder -> output.accept(withVariant(holder)));
		}
	}

	/** A painting item carrying the variant; a plain painting if the variant is missing (e.g. data pack removed it). */
	public static ItemStack paintingStack(HolderLookup.@Nullable Provider registries, Masterpiece art) {
		return variant(registries, art).map(PaintingContent::withVariant).orElseGet(() -> new ItemStack(Items.PAINTING));
	}

	private static Optional<Holder<PaintingVariant>> variant(HolderLookup.@Nullable Provider registries, Masterpiece art) {
		if (registries == null) {
			return Optional.empty();
		}
		try {
			return registries.lookup(Registries.PAINTING_VARIANT).flatMap(lookup -> lookup.get(art.key())).map(holder -> holder);
		} catch (RuntimeException e) {
			LaptopCraft.LOGGER.warn("Could not look up painting variant {}", art.id(), e);
			return Optional.empty();
		}
	}

	private static ItemStack withVariant(Holder<PaintingVariant> holder) {
		ItemStack stack = new ItemStack(Items.PAINTING);
		stack.set(DataComponents.PAINTING_VARIANT, holder);
		return stack;
	}
}
