#!/usr/bin/env python3
"""Packs the photo textures used by "Vice City" into one JS module.

The textures are CC0 scans from Poly Haven (https://polyhaven.com, public
domain). They are downloaded at 1k, shrunk (512px colour, 256px normal maps),
and written as base64 JPEGs to public/js/places/vice/assets/texdata.js so the
place works offline and inside the single-file standalone build.

Usage: python3 tools/pack-vice-textures.py [cache_dir]
"""
import base64
import io
import json
import os
import sys
import urllib.request

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'public', 'js', 'places', 'vice', 'assets', 'texdata.js')
CACHE = sys.argv[1] if len(sys.argv) > 1 else '/tmp/ph'

# (key, Poly Haven asset, normal map?) - one texture array, in this order
TEX = [
    ('asphalt', 'clean_asphalt', True),
    ('asphaltWorn', 'asphalt_04', True),
    ('sidewalk', 'concrete_pavement', True),
    ('pavers', 'concrete_pavers', True),
    ('herringbone', 'herringbone_concrete_tile', True),
    ('brickPave', 'brick_pavement', True),
    ('lawn', 'leafy_grass', True),
    ('sand', 'coast_sand_01', True),
    ('wetSand', 'damp_beach_sand', True),
    ('stucco', 'white_stucco', True),
    ('plaster', 'painted_plaster_wall', True),
    ('facade', 'concrete_tile_facade', True),
    ('cladding', 'rectangular_facade_tiles', True),
    ('concrete', 'brushed_concrete', True),
    ('blockWall', 'concrete_block_wall', True),
    ('brick', 'brick_wall_001', True),
    ('marble', 'marble_01', True),
    ('floorTiles', 'large_floor_tiles_02', True),
    ('whiteTiles', 'long_white_tiles', True),
    ('roofTiles', 'clay_roof_tiles', True),
    ('deck', 'wood_floor_deck', True),
    ('metalSheet', 'box_profile_metal_sheet', True),
    ('shutter', 'painted_metal_shutter', True),
    ('rust', 'rusty_metal_02', True),
    ('palmBark', 'palm_tree_bark', True),
    ('gravel', 'gravel_road', True),
]


def fetch(asset, kind):
    sub = 'nor' if kind == 'nor_gl' else ''
    path = os.path.join(CACHE, sub, asset + '.jpg') if sub else os.path.join(CACHE, asset + '.jpg')
    if not os.path.exists(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # ask the API where the file is (most colour maps are '_diff', a few are '_col')
        req = urllib.request.Request(f'https://api.polyhaven.com/files/{asset}', headers={'User-Agent': 'vice-texture-packer'})
        with urllib.request.urlopen(req) as r:
            files = json.load(r)
        url = files['Diffuse' if kind == 'diff' else kind]['1k']['jpg']['url']
        print('downloading', url)
        urllib.request.urlretrieve(url, path)
    return Image.open(path).convert('RGB')


def jpeg(img, size, q):
    img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, 'JPEG', quality=q, optimize=True, progressive=False)
    return 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode('ascii'), img


def pack(entries):
    out = []
    for key, asset, nor in entries:
        col, small = jpeg(fetch(asset, 'diff'), 512, 80)
        avg = small.resize((1, 1), Image.LANCZOS).getpixel((0, 0))
        item = {'key': key, 'src': asset, 'avg': '#%02x%02x%02x' % avg, 'col': col}
        if nor:
            item['nor'], _ = jpeg(fetch(asset, 'nor_gl'), 256, 86)
        out.append(item)
    return out


def main():
    items = pack(TEX)
    lines = [
        '// generated by tools/pack-vice-textures.py - do not edit.',
        '// Photo textures: CC0 scans from Poly Haven (polyhaven.com), shrunk to 512px (normal maps 256px).',
        'export const TEX = [',
    ]
    for it in items:
        lines.append('  ' + json.dumps(it, separators=(',', ':')) + ',')
    lines.append('];')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', OUT, round(os.path.getsize(OUT) / 1024 / 1024, 2), 'MB')


if __name__ == '__main__':
    main()
