#!/usr/bin/env python3
"""Packs the photo textures used by "The Outbreak" into one JS module.

The textures are CC0 scans from Poly Haven (https://polyhaven.com, public
domain). They are downloaded at 1k, shrunk (512px colour, 256px normal maps),
and written as base64 JPEGs to public/js/places/outbreak/texdata.js so the
place works offline and inside the single-file standalone build.

Usage: python3 tools/pack-outbreak-textures.py [cache_dir]
"""
import base64
import io
import json
import os
import sys
import urllib.request

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'public', 'js', 'places', 'outbreak', 'texdata.js')
CACHE = sys.argv[1] if len(sys.argv) > 1 else '/tmp/ph'

# (key, Poly Haven asset, normal map?)
GROUND = [
    ('grass', 'sparse_grass', True),
    ('meadow', 'forrest_ground_01', True),
    ('forest', 'forest_leaves_04', True),
    ('dirt', 'dirt', True),
    ('rock', 'rock_face_03', True),
    ('moss', 'mossy_rock', True),
    ('sand', 'coast_sand_01', True),
    ('gravel', 'rocks_ground_01', True),
    ('field', 'brown_mud_02', True),
]
SURF = [
    ('plaster', 'plastered_wall', True),
    ('plasterOld', 'worn_plaster_wall', True),
    ('stucco', 'concrete_wall_003', True),
    ('brick', 'red_brick', True),
    ('brickOld', 'brick_wall_02', True),
    ('panel', 'concrete_slab_wall', True),
    ('concrete', 'brushed_concrete', True),
    ('roofTile', 'clay_roof_tiles_02', True),
    ('roofSlate', 'red_slate_roof_tiles_01', True),
    ('metal', 'corrugated_iron_02', True),
    ('metalRust', 'rusty_corrugated_iron', True),
    ('planks', 'brown_planks_05', True),
    ('woodFloor', 'old_wood_floor', True),
    ('tiles', 'floor_tiles_06', True),
    ('container', 'container_side', True),
    ('rust', 'rusty_metal_02', True),
    ('pavement', 'concrete_pavement', True),
    ('pavers', 'pavement_03', True),
    ('asphalt', 'asphalt_02', True),
    ('track', 'muddy_tracks', True),
    ('bark', 'pine_bark', True),
    ('bark2', 'bark_willow', True),
]


def fetch(asset, kind):
    sub = 'nor' if kind == 'nor_gl' else ''
    path = os.path.join(CACHE, sub, asset + '.jpg') if sub else os.path.join(CACHE, asset + '.jpg')
    if not os.path.exists(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        url = f'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/{asset}/{asset}_{kind}_1k.jpg'
        print('downloading', url)
        urllib.request.urlretrieve(url, path)
    return Image.open(path).convert('RGB')


def jpeg(img, size, q):
    img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, 'JPEG', quality=q, optimize=True, progressive=False)
    return 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode('ascii'), img


def pack(entries):
    out = []
    for key, asset, nor in entries:
        col, small = jpeg(fetch(asset, 'diff'), 512, 80)
        avg = small.resize((1, 1), Image.LANCZOS).getpixel((0, 0))
        item = {'key': key, 'src': asset, 'avg': '#%02x%02x%02x' % avg, 'col': col}
        if nor:
            item['nor'], _ = jpeg(fetch(asset, 'nor_gl'), 256, 86)
        out.append(item)
    return out


def main():
    data = {'ground': pack(GROUND), 'surf': pack(SURF)}
    lines = [
        '// generated by tools/pack-outbreak-textures.py - do not edit.',
        '// Photo textures: CC0 scans from Poly Haven (polyhaven.com), shrunk to 512px (normal maps 256px).',
    ]
    for group, items in data.items():
        lines.append(f'export const {group.upper()} = [')
        for it in items:
            lines.append('  ' + json.dumps(it, separators=(',', ':')) + ',')
        lines.append('];')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', OUT, round(os.path.getsize(OUT) / 1024 / 1024, 2), 'MB')


if __name__ == '__main__':
    main()
